# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fine_tune_pb2 as fine__tune__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fine_tune_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FineTuneStub(object):
    """Fine-tuning service for dataset curation and model fine-tuning
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/fine_tune.FineTune/SubmitJob',
                request_serializer=fine__tune__pb2.SubmitRequest.SerializeToString,
                response_deserializer=fine__tune__pb2.SubmitResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/fine_tune.FineTune/GetStatus',
                request_serializer=fine__tune__pb2.StatusRequest.SerializeToString,
                response_deserializer=fine__tune__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/fine_tune.FineTune/CancelJob',
                request_serializer=fine__tune__pb2.CancelRequest.SerializeToString,
                response_deserializer=fine__tune__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.DeleteJob = channel.unary_unary(
                '/fine_tune.FineTune/DeleteJob',
                request_serializer=fine__tune__pb2.DeleteRequest.SerializeToString,
                response_deserializer=fine__tune__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/fine_tune.FineTune/ListJobs',
                request_serializer=fine__tune__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=fine__tune__pb2.ListJobsResponse.FromString,
                _registered_method=True)
        self.GetJobLogs = channel.unary_stream(
                '/fine_tune.FineTune/GetJobLogs',
                request_serializer=fine__tune__pb2.JobLogsRequest.SerializeToString,
                response_deserializer=fine__tune__pb2.JobLogEntry.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/fine_tune.FineTune/GetHealth',
                request_serializer=fine__tune__pb2.HealthRequest.SerializeToString,
                response_deserializer=fine__tune__pb2.HealthResponse.FromString,
                _registered_method=True)


class FineTuneServicer(object):
    """Fine-tuning service for dataset curation and model fine-tuning
    """

    def SubmitJob(self, request, context):
        """Submit a new fine-tuning job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get job status and logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Cancel a running job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteJob(self, request, context):
        """Delete a job (completed, failed, or cancelled jobs only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """List all jobs (with optional filtering)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobLogs(self, request, context):
        """Get job logs (streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FineTuneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=fine__tune__pb2.SubmitRequest.FromString,
                    response_serializer=fine__tune__pb2.SubmitResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=fine__tune__pb2.StatusRequest.FromString,
                    response_serializer=fine__tune__pb2.StatusResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=fine__tune__pb2.CancelRequest.FromString,
                    response_serializer=fine__tune__pb2.CancelResponse.SerializeToString,
            ),
            'DeleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteJob,
                    request_deserializer=fine__tune__pb2.DeleteRequest.FromString,
                    response_serializer=fine__tune__pb2.DeleteResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=fine__tune__pb2.ListJobsRequest.FromString,
                    response_serializer=fine__tune__pb2.ListJobsResponse.SerializeToString,
            ),
            'GetJobLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.GetJobLogs,
                    request_deserializer=fine__tune__pb2.JobLogsRequest.FromString,
                    response_serializer=fine__tune__pb2.JobLogEntry.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=fine__tune__pb2.HealthRequest.FromString,
                    response_serializer=fine__tune__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fine_tune.FineTune', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fine_tune.FineTune', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FineTune(object):
    """Fine-tuning service for dataset curation and model fine-tuning
    """

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fine_tune.FineTune/SubmitJob',
            fine__tune__pb2.SubmitRequest.SerializeToString,
            fine__tune__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fine_tune.FineTune/GetStatus',
            fine__tune__pb2.StatusRequest.SerializeToString,
            fine__tune__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fine_tune.FineTune/CancelJob',
            fine__tune__pb2.CancelRequest.SerializeToString,
            fine__tune__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fine_tune.FineTune/DeleteJob',
            fine__tune__pb2.DeleteRequest.SerializeToString,
            fine__tune__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fine_tune.FineTune/ListJobs',
            fine__tune__pb2.ListJobsRequest.SerializeToString,
            fine__tune__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fine_tune.FineTune/GetJobLogs',
            fine__tune__pb2.JobLogsRequest.SerializeToString,
            fine__tune__pb2.JobLogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fine_tune.FineTune/GetHealth',
            fine__tune__pb2.HealthRequest.SerializeToString,
            fine__tune__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
